### ISSUE TITLE
[Feature request] Clean docker images

### ISSUE THREAD

**Issue by eMerzh** [woubuc/sweep#18]
Hello, 
nice project!
it could be really nice if this could also clear up outdated docker images...
not sure how we can link it to specific folder though 🤔

**Comment by woubuc** [comment]
Interesting idea! Docker images aren't kept in a code directory so they're not going to be discovered by the crawler, unless you run it on your entire system (which you probably shouldn't do). So how would you see this feature working?

**Comment by eMerzh** [comment]
yeah i know, not really tight to directory...
could either be some generic `docker image prune -a` or via name 🤷‍♂️ ...

**Comment by woubuc** [comment]
My question then becomes: if you already have a simple command to clean up Docker images (`docker image prune`), why would you need this tool to support it as well?

**Comment by eMerzh** [comment]
my idea was, as much as i can cleanup my node_modules easily, it's something i don't think of so often.
And having a single go-to command to clean "dev and build things" seems interesting...
that said, it's clearly a bit out of the scope and might not be n°1 priority ;-)

**Comment by woubuc** [comment]
Yeah, I'm gonna go with out of scope on this one. I get where you're coming from, but I don't think it's something that Sweep should do. It would add a fair amount of additional code that needs to be tested and maintained, for very little benefit over just running e.g. `swp ~/dev && docker image prune`.

You could perhaps set up something for yourself that runs both those commands using `alias` or a `.sh`/`.bat` file.
